### ISSUE TITLE
Using Chai Expect/Assert

### ISSUE THREAD

**Issue by andyslack** [jdrydn/mocha-axios#5]
Hi Guys,

Love what you have here, I would like to know the best way to take the result of the API request and run Chai testing on them.

For example, if I query an auth endpoint with a username and password, I get back a token.

I would like to do something like:

`expect(res.body.token).to.be.a('String')`

Is there a way to return the result of the request into a local value for interrogation?

**Comment by jdrydn** [comment]
@andyslack Hey man, thanks for opening this 👍

> I would like to do something like:
> `expect(res.body.token).to.be.a('String')`

You could override the result with [`withModify`](https://github.com/jdrydn/mocha-axios#modify):

```js
const integration = require('mocha-axios');

// Set res-modify to anything you want
integration.with('res-modify', require('mocha-axios/withModify'));

it('should fetch a member profile', integration({
  app,
  req: {
    method: 'GET',
    url: '/member/2321/',
  },
  res: {
    status: 200,
    modify: {
      'token': 'SOME-TOKEN',
      'user.id': 'some-user-id',
    },
    data: {
      token: 'SOME-TOKEN',
      user: {
        id: 'some-user-id',
        username: 'jdrydn',
        created_date: 'YESTERDAY',
      },
    },
  },
}));
```

But this'll stop you from getting the value of your token for future requests. Perhaps a different set of hooks would be beneficial here?

> Another use case is to save the result, e.g. an order_id for future calls to endpoints.

That can easily be achieved using the `after` function:

```js
let token = null;

it('should fetch a member profile', integration({
  app,
  req: {
    method: 'GET',
    url: '/member/2321/',
  },
  res: {
    status: 200,
  },
  after({ res }) {
    ({ token } = res.body);
    expect(res.body.token).to.be.a('String');
  },
}));
```

Admittedly, it's been a while since I wrote this & the documentation, perhaps a refresh is due! If you have any other feedback I'd love to hear it to influence the refresh!

Thanks!
